### ISSUE TITLE
There is no “Show/Hide comment” for Team Fortress 2.

### ISSUE THREAD

**Issue by 219690858** [AbdelrahmanMerdan/MyGamingList#11]
<img width="644" alt="Screenshot 2024-03-24 at 9 06 46 PM" src="https://github.com/AbdelrahmanMerdan/MyGamingList/assets/158077696/8f7477a7-98cd-4507-b695-9fc1cb918151">

**Comment by richarc-yorku** [comment]
added review word wrap which fixed the issue
