### ISSUE TITLE
cannot comment on your own reviews in the "my reviews" menu

### ISSUE THREAD

**Issue by richarc-yorku** [AbdelrahmanMerdan/MyGamingList#17]
**Description:**
if you attempt to comment on reviews from the My Reviews menu, an out of bounds error is given and reviews cannot be added.

**How to Reproduce**
login and attempt to comment on a review from the My Reviews menu.

**Recommendation**
probably an issue with one of the database classes, double check interactions with the My Reviews menu.

**Comment by Alelixir** [comment]
Changed the review function to get the game of the user review from the user review instead of the GUI of the game loaded in
