### ISSUE TITLE
Remove Friend Yes/No/Cancel Prompt

### ISSUE THREAD

**Issue by richarc-yorku** [AbdelrahmanMerdan/MyGamingList#9]
- **Description:** 
   Prompt to remove friend provides Yes/No/Cancel as options where only one negative option is required 
- **Steps to Reproduce:** 
   Attempt to remove friend  
- **Recommendation:** 
   Modify JOption Panel to only allow a Yes/No response 
- **Severity:**
   Low

**Comment by 217761651** [comment]
Issue has been resolved, Only a Yes/No option is now available when removing a friends instead of Yes/No/Cancel
